name: pps_tablet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.29+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.3.0
  shimmer: ^2.0.0
  flutter_speed_dial: ^6.0.0
  mobile_scanner: ^6.0.5
  permission_handler: ^11.1.0
  shared_preferences: ^2.0.8
  flutter_searchable_dropdown: ^2.0.0
  dropdown_search: ^5.0.6
  searchfield: ^1.2.4
  vibration: ^3.1.3
  pdf: ^3.6.0
  printing: ^5.5.0
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  audioplayers: ^6.4.0
  fluttertoast: ^8.0.9
  smb_connect: ^0.0.9
  package_info_plus: ^8.0.0
  flutter_dotenv: ^5.2.1
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  socket_io_client: ^3.1.2
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  infinite_scroll_pagination: ^5.1.1
  material_design_icons_flutter: ^7.0.7296
  flutter_vector_icons: ^2.0.0
  dio: ^5.7.0
  open_filex: ^4.5.0




  # üü¢ THERMAL PRINTER ESC/POS
  flutter_blue_plus: ^1.32.0
  # ‚ùå HAPUS pdf_render - tidak compatible!
  # pdf_render: ^1.4.11
  image: ^4.2.0
  esc_pos_utils_plus: ^2.0.1  # ‚Üê TAMBAH INI

  cupertino_icons: ^1.0.8
  logging: ^1.3.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/fonts/Helvetica.ttf
    - assets/images/check.png
    - assets/images/cross.png
    - assets/images/icon_without_bg.png
    - assets/sounds/accepted.mp3
    - assets/sounds/denied.mp3
    - assets/animations/loading.json
    - assets/animations/success.json
    - assets/animations/error.json
    - assets/animations/scan.json
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  android_12:
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#ffffff"

dependency_overrides:
  image: ^4.2.0